(function(root){
  'use strict';
  const VERSION='1.0.0';
  const SAVING_SHEET_ID='1-QG1tnH0iTYLAzweJ6Gvj5JDN5p1YKIq9IONyvVIo4U';
  const DISPLAY_YEARS=[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100];
  const cache={};
  const cleanNum=value=>parseInt(String(value).replace(/[^\d]/g,''),10)||0;
  const fmtMoney=value=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(Math.round(value));
  function parseCSV(text){let rows=[],row=[],col='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],next=text[i+1];if(c==='"'&&quoted&&next==='"'){col+=c;i++;continue}if(c==='"'){quoted=!quoted;continue}if(c===','&&!quoted){row.push(col);col='';continue}if(c==='\r'&&!quoted)continue;if(c==='\n'&&!quoted){row.push(col);rows.push(row);row=[];col='';continue}col+=c}if(col!=='')row.push(col);if(row.length)rows.push(row);return rows}
  function parseSavingRows(rows){const parsed=[];for(let i=1;i<rows.length;i++){if(rows[i].length<3)continue;const year=parseInt(rows[i][0].replace(/,/g,''),10);const rate=parseFloat(rows[i][1].replace(/,/g,''));const mult=parseFloat(rows[i][2].replace(/,/g,''));if(!Number.isNaN(year)&&!Number.isNaN(rate)&&!Number.isNaN(mult))parsed.push({year,rate,mult})}return parsed}
  function interpolatedMultiplier(data,year){if(!data.length)return 0;if(year<=data[0].year)return data[0].mult*(year/data[0].year);if(year>=data[data.length-1].year)return data[data.length-1].mult;for(let i=0;i<data.length-1;i++){if(year>=data[i].year&&year<=data[i+1].year){const a=data[i],b=data[i+1];return a.mult+(b.mult-a.mult)*((year-a.year)/(b.year-a.year))}}return 0}
  function extractionStart(plan,data){if(!data.length||data[0].rate<=0)return 999;if(plan.includes('1year'))return 1;if(plan.includes('3year'))return 3;if(plan.includes('5year'))return 5;return 999}
  function calculateSaving({principal,startAge,plan,data,displayYears=DISPLAY_YEARS}){const start=extractionStart(plan,data);const rate=data.length?data[0].rate:0;let previousBalance=principal,previousYear=0;return displayYears.filter(year=>startAge+year<=100).map(year=>{const annual=year>=start?principal*rate:0;const cumulative=year>=start?annual*(year-start+1):0;const balance=principal*interpolatedMultiplier(data,year);let interest=null;if(plan==='自動滾存'){if(year===5)interest=(balance-principal)/principal;else if(year<=20)interest=(balance-previousBalance)/previousBalance;else interest=((balance-previousBalance)/previousBalance)/(year-previousYear)}const result={year,age:startAge+year,annual,cumulative,balance,interest};previousBalance=balance;previousYear=year;return result})}
  async function loadPlan(plan){if(cache[plan])return cache[plan];const url=`https://docs.google.com/spreadsheets/d/${SAVING_SHEET_ID}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(plan)}`;const response=await fetch(url);if(!response.ok)throw new Error(`HTTP ${response.status}`);cache[plan]=parseSavingRows(parseCSV(await response.text()));return cache[plan]}
  function setStatus(message,error=false){const el=document.getElementById('status');el.textContent=message;el.classList.toggle('is-error',error)}
  async function render(){const tbody=document.getElementById('saving-table-body');setStatus('正在連線 A+ 儲蓄庫…');tbody.innerHTML='';try{const plan=document.getElementById('saving-plan-select').value;const data=await loadPlan(plan);const rows=calculateSaving({principal:cleanNum(document.getElementById('saving-principal').value)||200000,startAge:parseInt(document.getElementById('saving-age').value,10)||40,plan,data});tbody.innerHTML=rows.map(row=>`<tr><td><strong>第 ${row.year} 年</strong>（${row.age}歲）</td><td>${row.annual?'$'+fmtMoney(row.annual):'--'}</td><td>${row.cumulative?'$'+fmtMoney(row.cumulative):'--'}</td><td>$${fmtMoney(row.balance)}</td><td class="interest-column" hidden>${row.interest===null?'--':(row.interest*100).toFixed(2)+'%'}</td></tr>`).join('');setStatus(`已載入 ${rows.length} 個年度結果`) }catch(error){console.error(error);setStatus('讀取失敗，請檢查網絡或 Google Sheet 權限。',true);tbody.innerHTML='<tr><td colspan="5">暫時未能載入資料</td></tr>'}}
  function setup(){const money=document.getElementById('saving-principal');money.addEventListener('input',()=>{const value=cleanNum(money.value);money.value=value?fmtMoney(value):'';render()});document.getElementById('saving-age').addEventListener('input',render);document.getElementById('saving-plan-select').addEventListener('change',render);document.getElementById('toggle-interest-btn').addEventListener('click',event=>{const expanded=event.currentTarget.getAttribute('aria-expanded')==='true';event.currentTarget.setAttribute('aria-expanded',String(!expanded));event.currentTarget.textContent=expanded?'顯示年息':'隱藏年息';document.getElementById('interest-heading').hidden=expanded;document.querySelectorAll('.interest-column').forEach(cell=>cell.hidden=expanded)});render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(console.warn)}
  root.SavingCore={VERSION,cleanNum,parseCSV,parseSavingRows,interpolatedMultiplier,calculateSaving};
  if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',setup);
})(typeof window!=='undefined'?window:globalThis);
